### ISSUE TITLE
ImportError: No module named 'beancount_web.util'

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#37]
When trying to start beancount-web after install, I get the following error:

```bash
$ beancount-web 
Traceback (most recent call last):
  File "/usr/local/bin/beancount-web", line 9, in <module>
    load_entry_point('beancount-web==0.1.0a1', 'console_scripts', 'beancount-web')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a1-py3.4.egg/beancount_web/cli.py", line 8, in <module>
    from beancount_web.api import BeancountReportAPI
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a1-py3.4.egg/beancount_web/api.py", line 27, in <module>
    from beancount_web.util.dateparser import parse_date
ImportError: No module named 'beancount_web.util'
```

"git-bisect" tells me:

```bash
a9b61255ba5bc3f4933c0a23bab748cb4cdd11e6 is the first bad commit
commit a9b61255ba5bc3f4933c0a23bab748cb4cdd11e6
Author: Jakob Schnitzer <mail@jakobschnitzer.de>
Date:   Fri Dec 11 14:17:25 2015 +0100

    use beancount.query for the filtering

:040000 040000 ca9f989836b11dd2cecefe20c5c6431dd01519dc e221fe28cbee06590563c6226cf08d2ae4117722 M	beancount_web
```

**Comment by aumayr** [comment]
Forgot to add new package to `setup.py`

Sorry for that, @corani
