### ISSUE TITLE
PermissionError when opening "statistics" page

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#38]
The `.webassets-cache` folder should probably be created by `setup.py`, since that's run with the correct privileges.

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/application.py", line 117, in report
    return render_template('{}.html'.format(report_name))
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/statistics.html", line 2, in top-level template code
    {% set active_page = 'statistics' %}
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/_layout.html", line 70, in top-level template code
    {% assets
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 474, in _merge_and_apply
    ctx.cache, no_cache_read=actually_skip_cache_here,
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 50, in __getattr__
    return self.getattr(self._parent, item)
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/bundle.py", line 58, in getattr
    return getattr(object, item)
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/env.py", line 438, in _get_cache
    cache = get_cache(self._storage['cache'], self)
  File "/usr/local/lib/python3.4/dist-packages/webassets-0.11.1-py3.4.egg/webassets/cache.py", line 231, in get_cache
    os.makedirs(directory)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/static/.webassets-cache'
```

**Comment by corani** [comment]
idem for the folder `/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/static/gen`

**Comment by aumayr** [comment]
Moved the target-folder for webassets to `static/stylesheets` because this folder already get's installed.

**Comment by aumayr** [comment]
See also 8068d4c8a0052bd69268818ca9e427af66bd34d6
