### ISSUE TITLE
Crashes upon clicking on any account

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#69]
c52710f crashes upon clicking any account name:

Using git bisect:
e6a49a9b6b798c0d4ceef19cd9ba05253967be84 is the first bad commit

jinja2.exceptions.TemplateSyntaxError
jinja2.exceptions.TemplateSyntaxError: unexpected ']', expected ')'

Traceback (most recent call last)
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/application.py", line 27, in account_with_journal
return account(account_name=name, with_journal=True)
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/application.py", line 51, in account
return render_template('account.html', account_name=account_name, journal=journal, linechart_data=linechart_data)
File "/usr/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
context, ctx.app)
File "/usr/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
rv = template.render(context)
File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/_account_name_header.html", line 15, in template
{% with status=api.is_account_uptodate(account_name, look_back_days=config.getint('uptodate-indicator-grey-lookback-days'])) %}
File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 986, in render
return concat(self.root_render_func(self.new_context(vars)))
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/account.html", line 2, in top-level template code
{% set active_page = 'trial_balance' %}
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/_layout.html", line 76, in top-level template code
{% block content %}{% endblock %}
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/account.html", line 13, in block "content"
{% include "_account_name_header.html" %}
File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.4/site-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/templates/_account_name_header.html", line 15, in template
{% with status=api.is_account_uptodate(account_name, look_back_days=config.getint('uptodate-indicator-grey-lookback-days'])) %}
File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 470, in _parse
return Parser(self, source, name, encode_filename(filename)).parse()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 897, in parse
result = nodes.Template(self.subparse(), lineno=1)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 879, in subparse
rv = self.parse_statement()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 121, in parse_statement
return getattr(self, 'parse_' + self.stream.current.value)()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 203, in parse_if
'name:endif'))
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 156, in parse_statements
result = self.subparse(end_tokens)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 879, in subparse
rv = self.parse_statement()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 128, in parse_statement
return ext(self)
File "/usr/lib/python3.4/site-packages/jinja2/ext.py", line 426, in parse
expr = parser.parse_expression()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 390, in parse_expression
return self.parse_condexpr()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 395, in parse_condexpr
expr1 = self.parse_or()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 408, in parse_or
left = self.parse_and()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 417, in parse_and
left = self.parse_not()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 428, in parse_not
return self.parse_compare()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 432, in parse_compare
expr = self.parse_add()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 454, in parse_add
left = self.parse_sub()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 464, in parse_sub
left = self.parse_concat()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 474, in parse_concat
args = [self.parse_mul()]
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 484, in parse_mul
left = self.parse_div()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 494, in parse_div
left = self.parse_floordiv()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 504, in parse_floordiv
left = self.parse_mod()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 514, in parse_mod
left = self.parse_pow()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 524, in parse_pow
left = self.parse_unary()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 543, in parse_unary
node = self.parse_postfix(node)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 672, in parse_postfix
node = self.parse_call(node)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 781, in parse_call
value = self.parse_expression()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 390, in parse_expression
return self.parse_condexpr()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 395, in parse_condexpr
expr1 = self.parse_or()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 408, in parse_or
left = self.parse_and()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 417, in parse_and
left = self.parse_not()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 428, in parse_not
return self.parse_compare()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 432, in parse_compare
expr = self.parse_add()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 454, in parse_add
left = self.parse_sub()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 464, in parse_sub
left = self.parse_concat()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 474, in parse_concat
args = [self.parse_mul()]
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 484, in parse_mul
left = self.parse_div()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 494, in parse_div
left = self.parse_floordiv()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 504, in parse_floordiv
left = self.parse_mod()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 514, in parse_mod
left = self.parse_pow()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 524, in parse_pow
left = self.parse_unary()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 543, in parse_unary
node = self.parse_postfix(node)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 672, in parse_postfix
node = self.parse_call(node)
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 786, in parse_call
args.append(self.parse_expression())
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 390, in parse_expression
return self.parse_condexpr()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 395, in parse_condexpr
expr1 = self.parse_or()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 408, in parse_or
left = self.parse_and()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 417, in parse_and
left = self.parse_not()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 428, in parse_not
return self.parse_compare()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 432, in parse_compare
expr = self.parse_add()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 454, in parse_add
left = self.parse_sub()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 464, in parse_sub
left = self.parse_concat()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 474, in parse_concat
args = [self.parse_mul()]
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 484, in parse_mul
left = self.parse_div()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 494, in parse_div
left = self.parse_floordiv()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 504, in parse_floordiv
left = self.parse_mod()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 514, in parse_mod
left = self.parse_pow()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 524, in parse_pow
left = self.parse_unary()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 542, in parse_unary
node = self.parse_primary()
File "/usr/lib/python3.4/site-packages/jinja2/parser.py", line 560, in parse_primary
next(self.stream)
File "/usr/lib/python3.4/site-packages/jinja2/lexer.py", line 349, in __next__
self.current = next(self._iter)
File "/usr/lib/python3.4/site-packages/jinja2/lexer.py", line 552, in wrap
for lineno, token, value in stream:
File "/usr/lib/python3.4/site-packages/jinja2/lexer.py", line 685, in tokeniter
filename)
jinja2.exceptions.TemplateSyntaxError: unexpected ']', expected ')'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by aumayr** [comment]
Arrrr! Thanks, @redstreet!

(Need to work on #36 to prevent this...)
