### ISSUE TITLE
Context view doesn't work

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#84]
When I click on any link to a `context` page, I get the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/application.py", line 104, in context
    context = app.api.context(ehash)
  File "/usr/local/lib/python3.4/dist-packages/beancount_web-0.1.0a2-py3.4.egg/beancount_web/api.py", line 786, in context
    self.entries, self.options, entry)
TypeError: render_entry_context() missing 2 required positional arguments: 'filename' and 'lineno'

**Comment by aumayr** [comment]
Does this happen for every `context`-link?

(I try to reproduce it, but for me all links work.)

**Comment by corani** [comment]
For every one I've seen so far. I'll try to do a little more digging.

**Comment by corani** [comment]
Ah, figured it out. After updating beancount to the latest version, the problem is fixed.

**Comment by aumayr** [comment]
:+1:

**Comment by brunov25** [comment]
I get the same problem with the latest beancount and fava (as of may 27, 2016)

the traceback from the command line where i run fava is different from the traceback in debug mode on the browser.  They are both very long.  Here is the last part for each:

from fava at the command line:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1660, in preprocess_request
    func(request.endpoint, request.view_args)
  File "/usr/local/lib/python3.4/dist-packages/fava/application.py", line 346, in pull_beancount_file
    g.beancount_file_slug = values.pop('bfile', None)
AttributeError: 'NoneType' object has no attribute 'pop'

----------------------------------------------------------------------------------------------------------------------------------
from the browser (when fava is in debug mode):



File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.4/dist-packages/fava/application.py", line 164, in context
return render_template('context.html', ehash=ehash)
File "/usr/lib/python3/dist-packages/flask/templating.py", line 127, in render_template
return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 812, in get_template
return self._load_template(name, self.make_globals(globals))
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 786, in _load_template
template = self.loader.load(self, name, globals)
File "/usr/local/lib/python3.4/dist-packages/jinja2/loaders.py", line 125, in load
code = environment.compile(source, name, filename)
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 565, in compile
self.handle_exception(exc_info, source_hint=source_hint)
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.4/dist-packages/fava/templates/context.html", line 16, in template
<dd><code><a href="{{ url_for_source(file_path=context.filename, line=context.lineno) }}" title="{{ _('Show source %(file)s:%(lineno)s', file=context.filename, context.lineno) }}">{{ context.filename }}:{{ context.lineno }}</a></code></dd>
File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 470, in _parse
return Parser(self, source, name, encode_filename(filename)).parse()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 897, in parse
result = nodes.Template(self.subparse(), lineno=1)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 879, in subparse
rv = self.parse_statement()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 121, in parse_statement
return getattr(self, 'parse_' + self.stream.current.value)()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 231, in parse_block
node.body = self.parse_statements(('name:endblock',), drop_needle=True)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 156, in parse_statements
result = self.subparse(end_tokens)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 879, in subparse
rv = self.parse_statement()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 121, in parse_statement
return getattr(self, 'parse_' + self.stream.current.value)()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 203, in parse_if
'name:endif'))
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 156, in parse_statements
result = self.subparse(end_tokens)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 871, in subparse
add_data(self.parse_tuple(with_condexpr=True))
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 616, in parse_tuple
args.append(parse())
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 390, in parse_expression
return self.parse_condexpr()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 395, in parse_condexpr
expr1 = self.parse_or()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 408, in parse_or
left = self.parse_and()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 417, in parse_and
left = self.parse_not()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 428, in parse_not
return self.parse_compare()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 432, in parse_compare
expr = self.parse_add()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 454, in parse_add
left = self.parse_sub()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 464, in parse_sub
left = self.parse_concat()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 474, in parse_concat
args = [self.parse_mul()]
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 484, in parse_mul
left = self.parse_div()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 494, in parse_div
left = self.parse_floordiv()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 504, in parse_floordiv
left = self.parse_mod()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 514, in parse_mod
left = self.parse_pow()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 524, in parse_pow
left = self.parse_unary()
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 543, in parse_unary
node = self.parse_postfix(node)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 672, in parse_postfix
node = self.parse_call(node)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 785, in parse_call
ensure(not kwargs)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 759, in ensure
token.lineno)
File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 50, in fail
raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: invalid syntax for function call expression
